apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer  # This specifies that you want a LoadBalancer
  ports:
    - port: 80          # The port exposed by the LoadBalancer
      targetPort: 5000  # The port your application listens on
  selector:
    app: flask-app      # Ensure this matches your deployment's labels