pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                  git branch: 'master', url: 'https://github.com/eshwar3240/code.git'
            }
        }
        stage('Terraform Init') {
            steps {
                dir('./terraformremote') { 
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir('./terraformremote'){ 
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
